version: "3"

services:
    nginx:
        depends_on:
            - wordpress
        build: requirements/nginx
        container_name: nginx
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - public
        ports:
            - "80:80"
            - "443:443"
        restart: always
    wordpress:
        depends_on:
            - db
        build: requirements/wordpress
        container_name: wordpress
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - public
            - private
        ports:
            - "9000:9000"
        environment:
            DOMAIN_NAME: ${DOMAIN_NAME}
            MYSQL_HOST: ${MYSQL_HOST}
            WP_DB_NAME: ${WP_DB_NAME}
            WP_DB_USER: ${WP_DB_USER}
            WP_DB_PASSWORD: ${WP_DB_PASSWORD}
            WP_TITLE: ${WP_TITLE}
            WP_ADMIN_USER: ${WP_ADMIN_USER}
            WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
            WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
            WP_USER: ${WP_USER}
            WP_PASSWORD: ${WP_PASSWORD}
            WP_EMAIL: ${WP_EMAIL}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
    db:
        build: requirements/mariadb
        container_name: db
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - private
        restart: always
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            WP_DB_NAME: ${WP_DB_NAME}
            WP_DB_USER: ${WP_DB_USER}
            WP_DB_PASSWORD: ${WP_DB_PASSWORD}
    ftp:
        build: requirements/ftp
        container_name: ftp
        volumes:
            - wordpress_data:/var/www/html
        ports:
            - "21:21"
            - "21100-21110:21100-21110"
        networks:
            - private
        restart: always
        environment:
            FTP_USER: ${FTP_USER}
            FTP_PASSWORD: ${FTP_PASSWORD}

volumes:
    db_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/inception_data/db
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/inception_data/db

networks:
    public:
    private:
